### ISSUE TITLE
Counter

### ISSUE THREAD

**Issue by p-runge** [Marvin-Dem/Tailwind-Designs#14]
Erstelle eine mini App, die in etwa so aussieht:

![Image](https://github.com/user-attachments/assets/beb68414-11fd-422a-8c70-e48a74219dbd)

# Ansätze

Du hast an dieser Stelle die Möglichkeit diese Aufgabe entweder mit nativem JavaScript bzw. TypeScript zu lösen, oder aber mit React.

Mit JS/TS hast du etwas weniger Boilerplate, mit React wird das Ganze aber ggf. etwas einfacher sein.

# ToDo

- [ ] Es gibt einen Text, der den aktuellen Wert des Counters darstellt (Default: 0)
- [ ] Es gibt einen Button, der den Wert um 1 erhöht
- [ ] Es gibt einen Button, der den Wert um 1 verringert
- [ ] Es gibt einen Button, der den Wert auf 0 zurücksetzt

# Hilfestellung

Solltest du Probleme bei der Aufgabe haben, gibt es hier eine Komplettanleitung für reines JavaScript:
https://www.youtube.com/watch?v=3PHXvlpOkf4&t=1825s

Ich würde dir aber empfehlen erstmal auf eigene Faust zu versuchen das Problem zu lösen.

**Comment by p-runge** [comment]
Ich habe einen PR in diesem Repo vorbereitet, der die React Boilerplate aufgesetzt hat: #13
