### ISSUE TITLE
Random Color Generator

### ISSUE THREAD

**Issue by p-runge** [Marvin-Dem/Tailwind-Designs#17]
Erstelle eine mini Web-App, die in etwa so aussieht:

![Image](https://github.com/user-attachments/assets/802dd08b-3dca-4747-9ea0-01bee55e028a)

# ToDo

- [x] Es gibt einen Button, der beim Klicken eine zufällige Farbe generiert
- [x] Es gibt einen Hintergrund, der die Farbe anzeigt
- [x] Es gibt einen Text, der die Farbe im Hexformat anzeigt

# Hinweis

Denk daran, wie sich Hex Codes von Farben zusammensetzen, und bedenke, dass es mehrere Arten gibt Farben darzustellen. Einige Arten eignen sich ggf. besser um sich zufällig generieren zu lassen als andere.
